sudo: required
dist: trusty
services: docker

language: ruby
rvm:
  - 2.3.1

before_install: gem update bundler

# Don't install gems in the :unit group by default
install: bundle install --jobs=3 --retry=3 --without unit

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-redhat-7
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-debian-7
    - INSTANCE=default-debian-8

script: kitchen verify ${INSTANCE}

# Run unit test on multiple Ruby versions
matrix:
  include:
  - script: bundle install --jobs=3 --retry=3 --with unit && rake test
    rvm: 2.1
  - script: bundle install --jobs=3 --retry=3 --with unit && rake test
    rvm: 2.2.5

# Ensure iptables is set up properly for Docker
# before_script:
  # - sudo iptables -L DOCKER || sudo iptables -N DOCKER


after_failure:
  - docker version
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log
